server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul
    username: root
    password: Esc141414!


  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  jwt:
    secret: arebfhvfbnfjvhbnejmcjdvnrhbgnfejcdnvhfrbnedjcnvhfejdmcjvfedmckfedjnmkcfjnefmkcdjn

